export const selectOccasionList = [
  {
    id: "1",
    title: "Seminar",
    desc: "Upcoming study event",
    icon: "🎓",
    field: "study",
  },
  {
    id: "2",
    title: "Date",
    desc: "Romantic outing planned",
    icon: "❤️",
    field: "social-activities",
  },
  {
    id: "3",
    title: "Meeting",
    desc: "Business-related discussion",
    icon: "💼",
    field: "Business",
  },
  {
    id: "4",
    title: "Exam",
    desc: "Important test approaching",
    icon: "📚",
    field: "study",
  },
  {
    id: "5",
    title: "Job Interview",
    desc: "Scheduled interview ahead",
    icon: "📝",
    field: "career",
  },
  {
    id: "6",
    title: "Family Event",
    desc: "Gathering with family",
    icon: "🏠",
    field: "personal-life",
  },
  {
    id: "7",
    title: "Vacation",
    desc: "Upcoming travel plans",
    icon: "✈️",
    field: "leisure",
  },
  {
    id: "8",
    title: "Health Check-up",
    desc: "Medical appointment planned",
    icon: "🏥",
    field: "health",
  },
  {
    id: "9",
    title: "Fitness Goal",
    desc: "Exercise or workout goal",
    icon: "💪",
    field: "health",
  },
  {
    id: "10",
    title: "Social Event",
    desc: "Upcoming party or event",
    icon: "🎉",
    field: "social-activities",
  },
  {
    id: "11",
    title: "Project Deadline",
    desc: "Work or study deadline",
    icon: "⏳",
    field: "work",
  },
  {
    id: "12",
    title: "Public Speaking",
    desc: "Speech or presentation",
    icon: "🎤",
    field: "personal-development",
  },
  {
    id: "13",
    title: "Financial Planning",
    desc: "Budget or savings goal",
    icon: "💰",
    field: "finance",
  },
  {
    id: "14",
    title: "Household Chores",
    desc: "Tasks around the house",
    icon: "🧹",
    field: "personal-life",
  },
  {
    id: "15",
    title: "Pet Care",
    desc: "Responsibility for pets",
    icon: "🐾",
    field: "personal-life",
  },
  {
    id: "16",
    title: "Hobby Pursuit",
    desc: "Focusing on a hobby",
    icon: "🎨",
    field: "leisure",
  },
  {
    id: "17",
    title: "Friendship",
    desc: "Relationship with friends",
    icon: "👥",
    field: "social-activities",
  },
  {
    id: "18",
    title: "Online Presence",
    desc: "Managing social media",
    icon: "📱",
    field: "personal-development",
  },
  {
    id: "19",
    title: "Skill Development",
    desc: "Learning something new",
    icon: "📖",
    field: "personal-development",
  },
  {
    id: "20",
    title: "Relocation",
    desc: "Moving to a new place",
    icon: "🚚",
    field: "personal-life",
  },
  {
    id: "21",
    title: "Conflict Resolution",
    desc: "Dealing with personal or work conflicts",
    icon: "⚔️",
    field: "personal-life",
  },
  {
    id: "22",
    title: "Financial Stress",
    desc: "Worry about expenses or debt",
    icon: "💳",
    field: "finance",
  },
  {
    id: "23",
    title: "Unemployment",
    desc: "Looking for a new job",
    icon: "🔍",
    field: "career",
  },
  {
    id: "24",
    title: "Breaking Bad News",
    desc: "Sharing unpleasant news with others",
    icon: "📉",
    field: "personal-life",
  },
  {
    id: "25",
    title: "Health Emergency",
    desc: "Sudden medical issue or crisis",
    icon: "🚑",
    field: "health",
  },
  {
    id: "26",
    title: "Legal Issues",
    desc: "Dealing with a legal matter or court case",
    icon: "⚖️",
    field: "personal-life",
  },
  {
    id: "27",
    title: "Public Criticism",
    desc: "Facing criticism or negative feedback",
    icon: "🗣️",
    field: "personal-development",
  },
  {
    id: "28",
    title: "Time Management Challenges",
    desc: "Struggling to manage time effectively",
    icon: "⏰",
    field: "work",
  },
  {
    id: "29",
    title: "Unplanned Expenses",
    desc: "Unexpected financial burden",
    icon: "💸",
    field: "finance",
  },
  {
    id: "30",
    title: "Home Repairs",
    desc: "Urgent household repairs needed",
    icon: "🔧",
    field: "personal-life",
  },
  {
    id: "31",
    title: "Workplace Uncertainty",
    desc: "Job insecurity or changes at work",
    icon: "🏢",
    field: "career",
  },
  {
    id: "32",
    title: "Relationship Struggles",
    desc: "Challenges in romantic relationships",
    icon: "💔",
    field: "social-activities",
  },
  {
    id: "33",
    title: "Moving to a New Job",
    desc: "Starting a new role or company",
    icon: "📈",
    field: "career",
  },
  {
    id: "34",
    title: "Physical Injury",
    desc: "Recovering from an injury",
    icon: "🩹",
    field: "health",
  },
  {
    id: "35",
    title: "Lack of Motivation",
    desc: "Feeling unmotivated in daily life",
    icon: "💤",
    field: "personal-development",
  },
  {
    id: "36",
    title: "Parenting Challenges",
    desc: "Stressful situations as a parent",
    icon: "👶",
    field: "personal-life",
  },
  {
    id: "37",
    title: "Career Transition",
    desc: "Changing career paths",
    icon: "🔄",
    field: "career",
  },
  {
    id: "38",
    title: "Social Anxiety",
    desc: "Fear of social interactions",
    icon: "😰",
    field: "social-activities",
  },
  {
    id: "39",
    title: "Self-Esteem Issues",
    desc: "Struggling with self-worth",
    icon: "💭",
    field: "personal-development",
  },
  {
    id: "40",
    title: "Long-Distance Relationship",
    desc: "Managing a relationship from afar",
    icon: "🌍",
    field: "social-activities",
  },
  {
    id: "41",
    title: "Midlife Crisis",
    desc: "Struggles with purpose and identity",
    icon: "🔄",
    field: "personal-life",
  },
  {
    id: "42",
    title: "Performance Review",
    desc: "Anxiety about work performance evaluation",
    icon: "📋",
    field: "career",
  },
  {
    id: "43",
    title: "Fear of Failure",
    desc: "Worries about not succeeding",
    icon: "🚫",
    field: "personal-development",
  },
  {
    id: "44",
    title: "Bullying",
    desc: "Dealing with harassment or bullying",
    icon: "👊",
    field: "social-activities",
  },
  {
    id: "45",
    title: "Homesickness",
    desc: "Missing home and loved ones",
    icon: "🏡",
    field: "personal-life",
  },
  {
    id: "46",
    title: "Climate Anxiety",
    desc: "Worries about environmental issues",
    icon: "🌍",
    field: "personal-development",
  },
  {
    id: "47",
    title: "Grief",
    desc: "Coping with loss or sadness",
    icon: "🖤",
    field: "personal-life",
  },
  {
    id: "48",
    title: "Conflict with Neighbors",
    desc: "Disputes with nearby residents",
    icon: "🏘️",
    field: "personal-life",
  },
  {
    id: "49",
    title: "Body Image Concerns",
    desc: "Struggles with self-image",
    icon: "🏋️",
    field: "health",
  },
  {
    id: "50",
    title: "Identity Crisis",
    desc: "Struggling with self-identity",
    icon: "❓",
    field: "personal-development",
  },
];

export const selectWorryList = [
  {
    id: "1",
    title: "Overthinking",
    desc: "Constantly analyzing situations and potential outcomes",
    icon: "🤔",
    field: "mental-health",
  },
  {
    id: "2",
    title: "Fear of Failure",
    desc: "Doubt about abilities and not meeting expectations",
    icon: "😟",
    field: "self-esteem",
  },
  {
    id: "3",
    title: "Performance Anxiety",
    desc: "Nervousness about performing well in public or important situations",
    icon: "😬",
    field: "stress",
  },
  {
    id: "4",
    title: "Imposter Syndrome",
    desc: "Feeling unworthy of success or doubting skills",
    icon: "🕵️‍♀️",
    field: "self-esteem",
  },
  {
    id: "5",
    title: "Time Management Issues",
    desc: "Worries about not having enough time to prepare or complete tasks",
    icon: "⏳",
    field: "productivity",
  },
  {
    id: "6",
    title: "Perfectionism",
    desc: "The need to do everything perfectly, leading to stress and procrastination",
    icon: "🏆",
    field: "mental-health",
  },
  {
    id: "7",
    title: "Social Anxiety",
    desc: "Fear of negative evaluation in social situations",
    icon: "😰",
    field: "social-activities",
  },
  {
    id: "8",
    title: "Uncertainty About the Future",
    desc: "Fear of unknown outcomes affecting life or career",
    icon: "🔮",
    field: "life-planning",
  },
  {
    id: "9",
    title: "Comparison with Others",
    desc: "Worrying about how one measures up to peers",
    icon: "📊",
    field: "self-esteem",
  },
  {
    id: "10",
    title: "Fear of Disappointing Others",
    desc: "Concern about letting down family, friends, or colleagues",
    icon: "😢",
    field: "relationships",
  },
  {
    id: "11",
    title: "Physical Symptoms of Stress",
    desc: "Experiencing stress-related physical issues like headaches or insomnia",
    icon: "💊",
    field: "health",
  },
  {
    id: "12",
    title: "Perceived Lack of Preparation",
    desc: "Feeling unprepared despite efforts, leading to self-doubt",
    icon: "📚",
    field: "study",
  },
  {
    id: "13",
    title: "Fear of Embarrassment",
    desc: "Worrying about making mistakes in front of others",
    icon: "😳",
    field: "social-activities",
  },
  {
    id: "14",
    title: "Lack of Control",
    desc: "Feeling helpless about upcoming events or situations",
    icon: "⚖️",
    field: "mental-health",
  },
];


//Initial Prompt

// export const AI_PROMPT =
// "I have a {work} in {days} days. I am bad and worried about my {worry1} and {worry2} and {worry3}. I want to improve my confidence and achieve success and {description}. Please provide me with a day-to-day plan and activities for each day(do not give like Day 1 - Day 2,  give Day 1, Day 2...) to perform in JSON format";

export const AI_PROMPT =
"{description}, My current stress level on a scale of 0 to 10 is {stressLevel}, I slept {SleepHours} hours last night, I had high anxiety/panic attacks {anxietyTimes} times yesterday, I had a {healthyLevel} level of Social Interaction on a scale of 0 to 10, My thought patterns were inconsistent with a value of {ynconstant} on a scale of 0 to 10, I had {physicalSympt} yesterday, I use {medications} for my mental health, and I have {occasion} approaching. Your name is Buddy and you are a trained mental health wellness instructor who has read the following books: The Body Keeps the Score, Be Calm: Proven Techniques to Stop Anxiety Now, Atomic Habits, “Light on Yoga” By B K S Iyenger, “A practical guide to Meditation” by OSHO, Eckhart Tolle's Power Of Now, It Didn't Start With You -Mark Wolynn, On Being A Therapist - Jeffrey Kottler, Pedagogy of the Oppressed by Paulo Freire and Louis Cozolino's making of a therapist and development of a therapist. Now you help me with generating my todays to-do list for my mental wellness, the list may include, How much water to drink, What type of meditation to perform and for what duration, what kind of activities I should be doing, whom to talk to, more activities for my mental wellness improvement in a perfect JSON format without missing any commas, the JSON should have the following structure: today's_wellness_plan object and this object should contain activities in activities object and then in every activity object we should have activity and rationale, This should be the structure and it should maintain uniformity";

// export const AI_PROMPT = 
//   "I have a {work} in {days} days. I am worried about my {worry1}, {worry2}, and {worry3}. I want to improve my confidence and achieve success. Provide me with a JSON-only day-to-day plan and activities with no additional explanations or text, please.";



  export const quotesList = [
    { id: "1", quote: "The only way to do great work is to love what you do. - Steve Jobs" },
    { id: "2", quote: "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston S. Churchill" },
    { id: "3", quote: "Don't watch the clock; do what it does. Keep going. - Sam Levenson" },
    { id: "4", quote: "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt" },
    { id: "5", quote: "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar" },
    { id: "6", quote: "Believe you can and you're halfway there. - Theodore Roosevelt" },
    { id: "7", quote: "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt" },
    { id: "8", quote: "It does not matter how slowly you go as long as you do not stop. - Confucius" },
    { id: "9", quote: "Your time is limited, don’t waste it living someone else’s life. - Steve Jobs" },
    { id: "10", quote: "Act as if what you do makes a difference. It does. - William James" },
    { id: "11", quote: "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau" },
    { id: "12", quote: "The only place where success comes before work is in the dictionary. - Vidal Sassoon" },
    { id: "13", quote: "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller" },
    { id: "14", quote: "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson" },
    { id: "15", quote: "Success is walking from failure to failure with no loss of enthusiasm. - Winston S. Churchill" },
    { id: "16", quote: "The way to get started is to quit talking and begin doing. - Walt Disney" },
    { id: "17", quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett" },
    { id: "18", quote: "Everything you’ve ever wanted is on the other side of fear. - George Addair" },
    { id: "19", quote: "Opportunities don't happen, you create them. - Chris Grosser" },
    { id: "20", quote: "Do what you can with all you have, wherever you are. - Theodore Roosevelt" },
    { id: "21", quote: "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett" },
    { id: "22", quote: "You are never too old to set another goal or to dream a new dream. - C.S. Lewis" },
    { id: "23", quote: "If you can dream it, you can achieve it. - Zig Ziglar" },
    { id: "24", quote: "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt" },
    { id: "25", quote: "The harder the conflict, the more glorious the triumph. - Thomas Paine" },
    { id: "26", quote: "Success is the sum of small efforts, repeated day in and day out. - Robert Collier" },
    { id: "27", quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson" },
    { id: "28", quote: "You miss 100% of the shots you don’t take. - Wayne Gretzky" },
    { id: "29", quote: "Limit your 'always' and your 'nevers.' - Amy Poehler" },
    { id: "30", quote: "What we fear doing most is usually what we most need to do. - Tim Ferriss" },
    { id: "31", quote: "The best way to predict the future is to create it. - Peter Drucker" },
    { id: "32", quote: "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh" },
    { id: "33", quote: "Success is not in what you have, but who you are. - Bo Bennett" },
    { id: "34", quote: "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll" },
    { id: "35", quote: "The secret of success is to be ready when your opportunity comes. - Benjamin Disraeli" },
    { id: "36", quote: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi" },
    { id: "37", quote: "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman" },
    { id: "38", quote: "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar" },
    { id: "39", quote: "Everything you can imagine is real. - Pablo Picasso" },
    { id: "40", quote: "Dream big and dare to fail. - Norman Vaughan" },
    { id: "41", quote: "You can’t use up creativity. The more you use, the more you have. - Maya Angelou" },
    { id: "42", quote: "If you want to lift yourself up, lift up someone else. - Booker T. Washington" },
    { id: "43", quote: "The future depends on what you do today. - Mahatma Gandhi" },
    { id: "44", quote: "It always seems impossible until it’s done. - Nelson Mandela" },
    { id: "45", quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson" },
    { id: "46", quote: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer" },
    { id: "47", quote: "You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne" },
    { id: "48", quote: "In order to succeed, we must first believe that we can. - Nikos Kazantzakis" },
    { id: "49", quote: "To succeed in life, you need three things: a wishbone, a backbone, and a funny bone. - Reba McEntire" },
    { id: "50", quote: "Success is getting what you want. Happiness is wanting what you get. - Dale Carnegie" },
  ];